language: python
# before_install:
# - export CHROME_BIN=chromium-browser
# - export DISPLAY=:99.0
# - sh -e /etc/init.d/xvfb start
sudo: false
dist: xenial
python:
 - "3.6"

node_js:
 - "10"

addons:
  chrome: stable

services:
  - xvfb
  - postgresql

before_script:
  - google-chrome --version
#  - wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
#  - wget https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_linux64.zip
#  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_`google-chrome --version | grep -o -E [0-9.]+`
  - mkdir driver
  - unzip chromedriver_linux64.zip -d $TRAVIS_BUILD_DIR/driver/
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/driver/
  - nvm install 10.10.0
  - git submodule -q foreach git pull -q origin master
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd $TRAVIS_BUILD_DIR/front
  - npm install
  - cd $TRAVIS_BUILD_DIR/back
  - pip install -r requirements.txt
  - ./manage.py migrate

script:
 - cd $TRAVIS_BUILD_DIR/front
 - nvm use node
 - node_modules/@angular/cli/bin/ng build -c test
 - npm start&
 - cd $TRAVIS_BUILD_DIR/back
 - xvfb-run ./manage.py test e2e.test_e2e

addons:
  postgresql: "9.6"

services:
  - postgresql

notifications:
  slack: ipponforge:POZIxDUMmeddHxK10Ub78v8j
