language: python
# before_install:
# - export CHROME_BIN=chromium-browser
# - export DISPLAY=:99.0
# - sh -e /etc/init.d/xvfb start
sudo: false
dist: trusty
python:
 - "3.6"

node_js:
 - "10"

before_script:
  - git submodule -q foreach git pull -q origin master
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd front
  - npm install
  - cd ../back
  - pip install -r requirements.txt
  - ./manage.py migrate

script:
 - cd front
 - node_modules/@angular/cli/bin/ng serve -c test
 - cd ../back
 - ./manage.py test e2e.e2e_test

addons:
  postgresql: "9.6"

services:
  - postgresql

notifications:
  slack: ipponforge:POZIxDUMmeddHxK10Ub78v8j
